In [1]:
import numpy as np

In [2]:
def NAND(a, b):
    return 1 - (a & b)  # NOT (a AND b)

In [9]:
NAND(2, 0)

1

In [11]:
1 - (2 & 1)

1

In [14]:
NAND(3, 3)

-2

In [15]:
# A NOT gate can be built by connecting both inputs of a NAND gate to the same value.

def NOT(a):
    return NAND(a, a)

# Test
print(NOT(0)) # Output: 1
print(NOT(1)) # Output: 0

1
0


In [17]:
NAND(1, 1)

0

In [18]:
# An AND gate can be built by negating the output of a NAND gate.

def AND(a, b):
    return NOT(NAND(a, b))

# Test
print(AND(0, 0))  # Output: 0
print(AND(0, 1))  # Output: 0
print(AND(1, 0))  # Output: 0
print(AND(1, 1))  # Output: 1

0
0
0
1


In [52]:
def OR(a, b):
    return NAND(NOT(a), NOT(b))

# Test
print(OR(0, 0))  # Output: 0
print(OR(0, 1))  # Output: 1
print(OR(1, 0))  # Output: 1
print(OR(1, 1))  # Output: 1

0
1
1
1


In [51]:
def XOR(a, b):
    c = NAND(a, b)
    return NAND(NAND(a, c), NAND(b, c))

In [53]:
def half_adder(A, B):
    S = XOR(A, B)  # Sum using XOR
    C = AND(A, B)  # Carry using AND
    return S, C

# Test
print(half_adder(0, 0))
print(half_adder(0, 1))
print(half_adder(1, 0))
print(half_adder(1, 1))

(0, 0)
(1, 0)
(1, 0)
(0, 1)


In [54]:
def full_adder(A, B, Cin):
    s, c = half_adder(A,   B)
    S, C = half_adder(Cin, s)
    Cout = OR(c, C)
    return S, Cout

# Test
print(full_adder(0, 0, 0))  # Output: (0, 0)
print(full_adder(1, 0, 0))  # Output: (1, 0)
print(full_adder(1, 1, 0))  # Output: (0, 1)
print(full_adder(1, 1, 1))  # Output: (1, 1)

(0, 0)
(1, 0)
(0, 1)
(1, 1)


In [55]:
def multibit_adder(A, B, carrybit=False):
    assert(len(A) == len(B))
    
    n = len(A)
    c = 0
    S = []
    for i in range(n):
        s, c = full_adder(A[i], B[i], c)
        S.append(s)
    if carrybit:
        S.append(c)  # add the extra carry bit
    return S

# Test
A = [1, 1, 0, 1]  # 1 + 2 + 8 = 11 in binary
B = [1, 0, 0, 1]  # 1 + 8 = 9 in binary
print(multibit_adder(A, B, carrybit=True))

[0, 0, 1, 0, 1]


In [62]:
n = len(A)
for i in range(n):
    s, c = full_adder(A[i], B[i], 0)
    print(c)

1
0
0
1


In [63]:
0b101

5

In [64]:
0b011

3

In [65]:
XOR(1, 1)

0

In [114]:
def multibit_negative(A):
    """Multi-bit integer negative operator

    This function take the binary number A and return negative A using
    two's complement.
    In other words, if the input
        A = 3 = 0b011,
    then the output is
        -A = -3 = 0b101.

    Args:
        A: input number in binary represented as a python list, with
           the least significant digit be the first.
           That is, the binary 0b011 should be given by [1,1,0].

    Returns:
        Negative A using two's complement represented as a python
        list, with the least significant digit be the first.

    """
    # TODO: implement the function here
    
    n = len(A)
    l = 1
    
    S = []
    for i in range(n):
        s = NOT(A[i])
        S.append(s)
        
    S[0] = XOR(S[0], l)

    
    return S

In [115]:
multibit_negative([1, 1, 0])

[1, 0, 1]

In [121]:
int("101")

101

In [93]:
XOR(S[-1], l)

1

In [91]:
A[-1]

1

In [83]:
0b0011

3

In [84]:
0b1101

13

In [86]:
XOR(0,1)

1

In [88]:
[0, 0, 0][-1]

0

In [107]:
one = [1]
for i in range(1, n):
    one.append(0)

print(one)

[1, 0, 0, 0]


In [116]:
one = [0 for _ in range(n)]
one[0] = 1

In [117]:
one

[1, 0, 0, 0]

In [135]:
def multibit_negative(A):
    n = len(A)
    
    # Invert all the bits
    INV = []
    for i in range(n):
        s = NOT(A[i])
        INV.append(s)
        
    # Setting the "1" list to add to the inverts
    l = [1] # So the first number will be 1
    for i in range(1, n):
        l.append(0)
        
    # Add 1 to the LSB
    Neg_A = multibit_adder(l, INV)

    
    return Neg_A

In [127]:
multibit_negative(B)

[1, 1, 1, 0]

In [137]:
multibit_negative(A)

[1, 0, 1, 0]

In [128]:
B

[1, 0, 0, 1]

In [129]:
def multibit_subtractor(A, B):
    """Multi-bit integer subtraction operator

    This function take the binary numbers A and B, and return A - B.
    Be careful on how the carrying bit is handled in multibit_adder().
    Make sure that when A == B, the result A - B should be zero.

    Args:
        A, B: input number in binary represented as a python list,
           with the least significant digit be the first.
           That is, the binary 0b011 should be given by [1,1,0].

    Returns:
        A - B represented as a python list, with the least significant
        digit be the first.

    """
    # TODO: implement the function here
    
    # take the binary number B and return negative B
    Neg_B = multibit_negative(B)
    
    # Adding A to -B becomes A - B
    Diff = multibit_adder(A, Neg_B)
    
    return Diff
    

In [130]:
multibit_subtractor(A, B)

[0, 1, 0, 0]

In [131]:
A

[1, 1, 0, 1]

In [132]:
B

[1, 0, 0, 1]

In [133]:
one = [0 for i in range(len(A))]
one[0] = 1

In [134]:
one

[1, 0, 0, 0]

In [139]:
[0 for i in range(n)]

[0, 0, 0, 0]

In [140]:
from math import exp

for tau in range(0, 60, 5):
    I = exp(tau) - (exp(tau) - 1.0)
    print(f"{tau=}, {I=}")

tau=0, I=1.0
tau=5, I=1.0
tau=10, I=1.0
tau=15, I=1.0
tau=20, I=1.0
tau=25, I=1.0
tau=30, I=1.0
tau=35, I=1.0
tau=40, I=0.0
tau=45, I=0.0
tau=50, I=0.0
tau=55, I=0.0


In [141]:
a = 1e-9
b = 1
c = 1e-9

x1 = (-b + (b*b - 4*a*c)**(1/2)) / (2*a)
x2 = (-b - (b*b - 4*a*c)**(1/2)) / (2*a)

print(f'{x1:.16f}, {x2:.16f}')

0.0000000000000000, -999999999.9999998807907104


In [142]:
x = 0
while x < 1:
    x += 0.1
    print(f"{x:g}")

0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1
1.1


In [143]:
x = 0
while x < 1:
    x += 0.1
    print(f"{x:.17f}")

0.10000000000000001
0.20000000000000001
0.30000000000000004
0.40000000000000002
0.50000000000000000
0.59999999999999998
0.69999999999999996
0.79999999999999993
0.89999999999999991
0.99999999999999989
1.09999999999999987


In [144]:
def simple_sum(x, n):
    s = 0.0
    for i in range(n):
        s += x
    return s


In [145]:
x = 0.1
n = 10
s = simple_sum(x, n)
e = abs(s/n - x) / x
print(f"Mean = {s}; relative error = {e}")

Mean = 0.9999999999999999; relative error = 1.3877787807814457e-16


In [146]:
# Demonstrate NaN comparison rules

import numpy as np

x = np.nan
y = 1

print(x != x)
print(x >  x)
print(x <  x)
print(x >= x)
print(x <= x)
print(x == x)

print(x != y)
print(x >  y)
print(x <  y)
print(x >= y)
print(x <= y)
print(x == y)

True
False
False
False
False
False
True
False
False
False
False
False


In [152]:
np.sign(-1)*1

np.int64(-1)

In [153]:
float(0)

0.0

In [166]:
def quadratic(a, b, c):
    """Numerically stable quadratic equation solver

    The standard quadratic formula

        x = (-b +- sqrt(b^2 - 4ac)) / (2a)

    is algebraically correct but can suffer from *catastrophic
    cancellation* when b^2 >> 4ac and the sign of b matches the
    chosen +-.
    In that case, subtracting two nearly equal numbers causes a large
    loss of precision.

    A more stable alternative is obtained by multiplying top and
    bottom by the conjugate, leading to two equivalent forms.
    To avoid cancellation, choose the version that keeps the
    subtraction well-separated:

        x1 = (-b - sign(b) * sqrt(b^2 - 4ac)) / (2a)
        x2 = (c / a) / x1

    This way, at least one root is always computed stably.

    Args:
        a, b, c: coefficients for the quadratic equation
                 a x^2 + b x + c = 0.

    Returns:
        x1, x2: the two roots of the quadratic equation.
                If there are two real roots, x1 < x2.
                If there is only one real root, x2 == None.
                If there is no real root, x1 == x2 == None.
    """
    # TODO: implement the stable quadratic equation solver here
        
    root = b**2 - 4*a*c
    
    # Checking if the roots are real
    if root < float(0):
        x_1, x_2 = None, None
    
    # If the roots are real, we can implement this formula to avoid cancellation
    else:
        x_1_form = (-b - np.sign(b)*np.sqrt(b**2 - 4*a*c))/(2*a)
        x_2_form = c/(a*x_1_form)
        
        # When there are 2 real roots
        if x_1_form < x_2_form:
            x_1, x_2 = x_1_form, x_2_form
            
        elif x_1_form > x_2_form:
            x_1, x_2 = x_2_form, x_1_form
        
        # When they are equal there is only 1 real root
        else:
            x_1, x_2 = x_1_form, None
            
    return x_1, x_2
    
    #int(x_1), int(x_2)

In [167]:
a = 1e-9
b = 1
c = 1e-9

quadratic(a, b, c)

(np.float64(-999999999.9999999), np.float64(-1.0000000000000003e-09))

In [168]:
def quadratic(a, b, c):
    """Numerically stable quadratic equation solver

    The standard quadratic formula

        x = (-b +- sqrt(b^2 - 4ac)) / (2a)

    is algebraically correct but can suffer from *catastrophic
    cancellation* when b^2 >> 4ac and the sign of b matches the
    chosen +-.
    In that case, subtracting two nearly equal numbers causes a large
    loss of precision.

    A more stable alternative is obtained by multiplying top and
    bottom by the conjugate, leading to two equivalent forms.
    To avoid cancellation, choose the version that keeps the
    subtraction well-separated:

        x1 = (-b - sign(b) * sqrt(b^2 - 4ac)) / (2a)
        x2 = (c / a) / x1

    This way, at least one root is always computed stably.

    Args:
        a, b, c: coefficients for the quadratic equation
                 a x^2 + b x + c = 0.

    Returns:
        x1, x2: the two roots of the quadratic equation.
                If there are two real roots, x1 < x2.
                If there is only one real root, x2 == None.
                If there is no real root, x1 == x2 == None.
    """
    if (b**2 - 4*a*c)<0.:
        x1 = None
        x2 = None 
    else:
        _x1 = (-b - np.sign(b) * np.sqrt(b**2 - 4*a*c)) / (2*a)
        _x2 = (c / a) / _x1
        if _x1<_x2:
            x1 = _x1
            x2 = _x2
        elif _x1>_x2:
            x1 = _x2
            x2 = _x1
        else: 
            x1 = _x1
            x2 = None
    return x1,x2

In [169]:
quadratic(a, b, c)

(np.float64(-999999999.9999999), np.float64(-1e-09))

In [195]:
X0=[-0.5, 0, 0.5]

m=1.0,

k=1.0

K = np.zeros((len(X0), len(X0)))
for i in range(K.shape[0]):
    for j in range(K.shape[1]):
        if i == j:
            K[i, j] = 2*k
        elif abs(i-j) == 1:
            K[i,j] = -1*k

In [196]:
K

array([[ 2., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  2.]])

In [197]:
eigenvalues, eigenvectors = np.linalg.eig(K / m)
Omega = np.sqrt(eigenvalues)

In [200]:
Omega

array([1.84775907, 1.41421356, 0.76536686])

In [202]:
eigenvectors

array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
       [ 7.07106781e-01,  6.68563842e-16,  7.07106781e-01],
       [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]])

In [205]:
M0 = np.linalg.solve(eigenvectors, X0)
M0

array([-2.79985784e-16,  7.07106781e-01, -3.88578059e-16])

In [210]:
modal = M0 * np.cos(Omega * 2)
modal

array([ 2.38118435e-16, -6.72715319e-01, -1.55632823e-17])

In [212]:
d = eigenvectors @ modal
d

array([ 4.75681564e-01, -2.92382881e-16, -4.75681564e-01])

In [187]:
eigenvalues, eigenvectors = np.linalg.eig(K / m)

In [213]:
K = np.zeros((3,3))
for i in range(3):
    if i == 0:
        K[i,i] = 2.
        K[i,i+1] = -1.
        continue
    if i == 3-1:
        K[i,i] = 2.
        K[i,i-1] = -1.
        continue
    K[i,i-1] = -1.
    K[i,i]   = 2.
    K[i,i+1] = -1.

K

array([[ 2., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  2.]])

In [215]:
X0 = np.array(X0)

In [216]:
Omegasqrd,eigenvecs = np.linalg.eig(K/m)
Omega = np.sqrt(Omegasqrd)
M0 = np.linalg.solve(eigenvecs, X0)

In [217]:
M0

array([-2.79985784e-16,  7.07106781e-01, -3.88578059e-16])

In [219]:
modal_positions =M0 * np.cos(Omega * 2)
eigenvecs @ modal_positions

array([ 4.75681564e-01, -2.92382881e-16, -4.75681564e-01])

In [220]:
s

0.9999999999999999